Add addModifiers option to valid-v-slot
vuejs/eslint-plugin-vue pull request #1330
Opened 2020-10-11 11:14 UTC by nokazn

## About

- resolve #1165 

Add `addModifiers` option to `valid-v-slot` rules. When this option is set to `true`, modifiers in the argument of `v-slot` are ignored, and invalid modifiers like `v-slot.foo` are still disallowed.

2020-10-11 12:06 UTC, ota-meshi requested changes
Thank you for this PR!
I have some change requests.

2020-10-11 12:06 UTC, ota-meshi commented on lib/rules/valid-v-slot.js
> +  return [sourceCode.getText(node.key.argument), ...modifierNames].join('.')
It works with this source as well, however can you change it as follows?

```js
return node.key.modifiers.length === 0 ?
  sourceCode.getText(node.key.argument) :
  sourceCode.text.slice(node.key.argument.range[0], node.key.range[1])
```

2020-10-11 12:06 UTC, ota-meshi commented on tests/lib/rules/valid-v-slot.js
> +    },
Could you add test cases to check that the following code will result in errors with `"allowModifiers: true"`?

```vue
<template>
<MyComponent>
<template v-slot:foo.bar></template>
<template v-slot:foo.bar></template>
</MyComponent>
</template>
```

2020-10-11 14:38 UTC, ota-meshi requested changes

2020-10-11 14:38 UTC, ota-meshi commented on tests/lib/rules/valid-v-slot.js
> +      options: [{ allowModifiers: true }],
Could you please revert this test case? Also, add new test cases if needed.

2020-10-11 15:01 UTC, nokazn commented on tests/lib/rules/valid-v-slot.js
> +      options: [{ allowModifiers: true }],
Sorry, I'll fix it.

2020-10-11 15:07 UTC, ota-meshi approved these changes
LGTM! Thank you!

2020-10-18 13:23 UTC, merged

2020-10-20 05:46 UTC, KaelWD commented
Why was this added as an option that's disabled by default? Vuetify uses `.` extensively in slot names, having it throw eslint errors is confusing for new developers. It shouldn't even be an option IMO, they aren't really "modifiers" as vue treats v-slot completely differently to normal directives.

2020-10-20 06:28 UTC, ota-meshi commented
Hi @KaelWD.
I know Vuetify is used by many people, but for non Vuetify users, using modifiers is almost mistake.
I think you should provide an ESLint sharable config for Vuetify. Its config turns on `allowModifiers`.