fix(eslint-plugin-vue): [valid-v-bind-sync] Added Case for Valid Is the Valid .sync
vuejs/eslint-plugin-vue pull request #1335
Opened 2020-10-17 18:48 UTC by aggmoulik

Fixes #1298 
Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

2020-10-18 00:23 UTC, ota-meshi requested changes
Thank you for this PR!
I have some change requests.

2020-10-18 00:23 UTC, ota-meshi commented on lib/rules/valid-v-bind-sync.js
> +    ['tr', 'li', 'option'].includes(node.parent.name)
Could you remove the element name check?
The `is` attribute can be used on all elements. There is no need to check the element name.

2020-10-18 00:23 UTC, ota-meshi commented on lib/rules/valid-v-bind-sync.js
> +    if (attr.type === 'VAttribute' && attr.key.name === 'is') return attr
We should also check `v-bind:is`.

2020-10-18 00:23 UTC, ota-meshi commented on lib/rules/valid-v-bind-sync.js
> +  const isAttribute = attributes.filter((attr) => {
Could you use `some` instead of `filter`.

2020-10-19 09:06 UTC, aggmoulik commented
Hy @ota-meshi I have updated your changes and added a cli utility also, as it helps us to check individual rules and makes our development faster.

2020-10-19 09:10 UTC, aggmoulik commented
Also, Add `hacktoberfest` label in the PR or in the repository tags.

2020-10-19 09:43 UTC, ota-meshi commented
I'm currently maintaining this repository almost alone, so I can't afford to accept all PR during the `hacktoberfest`, so I won't add `hacktoberfest` label.
Also, I'm sorry, this PR can't promise to complete all reviews and merge in October.

2020-10-19 09:56 UTC, aggmoulik commented
@ota-meshi I think I can help you in that as I am working to be a active-contributor not for just hacktoberfest. I can help in code review as I already do in my company.

2020-12-03 01:23 UTC, ota-meshi requested changes
Sorry for the late reply. I posted some comments.

2020-12-03 01:23 UTC, ota-meshi commented on lib/rules/valid-v-bind-sync.js
> +      if (attr.key.type === 'VDirectiveKey' && attr.key.argument.name === 'is')
You need to check if it is v-bind. Also, the argument can be null.

https://github.com/vuejs/vue-eslint-parser/blob/master/docs/ast.md#vdirectivekey

In addition, could you add a test to make sure it is not judged as `is`?

```vue
<tr v-on:is="myRow" :some-prop.sync="somePropValue">
<tr v-bind="myRow" :some-prop.sync="somePropValue">
```

2020-12-03 01:23 UTC, ota-meshi commented on package.json
> +    "tests": "mocha"
Do not change the script. You may be able to use `npx mocha`.

2020-12-03 01:23 UTC, ota-meshi commented on tests/lib/rules/valid-v-bind-sync.js
> +          <tr v-bind:is="my-row"
```suggestion
          <tr v-bind:is="myRow"
```

2020-12-04 03:59 UTC, ota-meshi commented on package.json
> +    "tests": "mocha"
```suggestion
    "docs:build": "vuepress build docs"
```

2020-12-04 04:01 UTC, ota-meshi commented
I would like to share the fix related to this issue with another fix. So I'll fix this PR and merge it.

2020-12-04 04:05 UTC, merged