Fixes #1379 Add since attribute
vuejs/eslint-plugin-vue pull request #1384
Opened 2020-12-17 15:13 UTC by ajmas

2020-12-18 00:44 UTC, ota-meshi requested changes
Thank you for your lot of work!
Could you restore the blanks at the end of line that were intended for line breaks?

2020-12-20 21:20 UTC, ajmas commented
I'll make the changes, though may be delayed slightly

2020-12-21 12:39 UTC, ota-meshi requested changes

2020-12-21 12:39 UTC, ota-meshi commented on docs/rules/README.md
> +---
```suggestion
```

2020-12-21 12:39 UTC, ota-meshi commented on docs/rules/html-comment-indent.md
> +---
```suggestion
description: enforce consistent indentation in HTML comments
since: v7.0.0
```

2020-12-21 12:41 UTC, ota-meshi approved these changes
Thank you!

2020-12-24 02:30 UTC, merged