Add composition api's computed function support to vue/no-async-in-computed-properties refs #1393
vuejs/eslint-plugin-vue pull request #1398
Opened 2020-12-30 07:39 UTC by sapphi-red

This PR adds support for composition api's computed function to `vue/no-async-in-computed-properties`.
refs #1393

2020-12-30 07:42 UTC, sapphi-red commented on docs/rules/no-async-in-computed-properties.md
> +description: disallow asynchronous actions in computed properties and functions
`computed values` maybe better?
I'm not sure how I should call it.

2021-01-02 03:40 UTC, ota-meshi requested changes

2021-01-02 03:40 UTC, ota-meshi commented on lib/utils/index.js
> +  getComputedGetterBody(callExpression) {
Can you rename it to include the meaning that it is a function that only accepts `computed (() => {})`?
Or change the argument to be acceptable and use this function in `getComputedProperties` as well.

```js
/**
  * @param {Expression} expr
  */
getComputedGetterBody(expr) {
}

// ...
// use
const getter = utils.getComputedGetterBody(node.arguments[0])
```

2021-01-02 03:40 UTC, ota-meshi commented on tests/lib/rules/no-async-in-computed-properties.js
> +      ]
Could you add test cases for the arrow function that omits return?

2021-01-02 03:40 UTC, ota-meshi commented on lib/rules/no-async-in-computed-properties.js
> +    const computedFunctionNodes = new Set()
You can probably do the same with an array. Since the array is simpler, can you change it to an array?

2021-01-02 11:20 UTC, sapphi-red commented
Thank you for reviewing! I fixed it.

2021-01-02 23:54 UTC, ota-meshi approved these changes
Looks good to me! Thank you!

2021-01-03 00:46 UTC, merged