Fix false positives for import binding in `vue/valid-define-emits` and `vue/valid-define-props` rules
vuejs/eslint-plugin-vue pull request #1736
Opened 2021-12-03 04:42 UTC by ota-meshi

close #1734

2021-12-03 07:58 UTC, FloEdelmann requested changes

2021-12-03 07:58 UTC, FloEdelmann commented on lib/rules/valid-define-emits.js
> +                  })
Wouldn't this be much more readable and also much more concise?

```suggestion
                  variable.defs.every(
                    (def) =>
                      def.type !== 'ImportBinding' &&
                      utils.inRange(scriptSetup.range, def.name) &&
                      !utils.inRange(defineEmits.range, def.name)
                  )
```

2021-12-03 07:58 UTC, FloEdelmann commented on lib/rules/valid-define-props.js
> +                  })
And again:

```suggestion
                  variable.defs.every(
                    (def) =>
                      def.type !== 'ImportBinding' &&
                      utils.inRange(scriptSetup.range, def.name) &&
                      !utils.inRange(defineEmits.range, def.name)
                  )
```

2021-12-03 11:06 UTC, ota-meshi commented
Thank you for your review! I changed this PR.

2021-12-03 12:14 UTC, FloEdelmann approved these changes

2021-12-03 14:23 UTC, merged

2022-05-31 09:56 UTC, baixiaoyu2997 commented
hi ,does this plugin now support  verify `defineEmits(['onSuccess'])` case?  
like :
```
defineEmits(['onSuccess'])  // bad
defineEmits(['on-success'])  // good
```