Add `prefer-true-attribute-shorthand` rule
vuejs/eslint-plugin-vue pull request #1796
Opened 2022-02-09 09:56 UTC by g-plane

Closes #775 
Closes #1781

2022-02-09 10:17 UTC, ota-meshi approved these changes
LGTM! Thank you!

2022-02-09 11:55 UTC, FloEdelmann requested changes
Thanks for implementing this! However, I have a few remarks.

In https://github.com/vuejs/eslint-plugin-vue/issues/775#issuecomment-454081818, it was suggested to make it configurable whether to always or never use shorthand props. I think that's a good idea, given some people may prefer to never use shorthand props because of their quirks or just by taste.

The `never` case could also be auto-fixable, while the suggestion you implemented would be fine for the `always` case.

2022-02-09 11:55 UTC, FloEdelmann commented on lib/rules/prefer-true-attribute-shorthand.js
> +        'require shorthand form attribute when `v-bind` value is `true`.',
To stay consistent with other descriptions:

```suggestion
        'require shorthand form attribute when `v-bind` value is `true`',
```

2022-02-09 11:55 UTC, FloEdelmann commented on lib/rules/prefer-true-attribute-shorthand.js
> +    type: 'problem',
It's only a stylistic/conventional choice, not a problem.

```suggestion
    type: 'suggestion',
```

2022-02-09 11:55 UTC, FloEdelmann commented on lib/rules/prefer-true-attribute-shorthand.js
> +    return utils.defineTemplateBodyVisitor(context, {
Please remove the boilerplate comment and empty line:

```suggestion
    return utils.defineTemplateBodyVisitor(context, {
```

2022-02-09 11:55 UTC, FloEdelmann commented on docs/rules/prefer-true-attribute-shorthand.md
> +Those two calls will introduce different render result. See [this demo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBNeUNvbXBvbmVudCBmcm9tICcuL015Q29tcG9uZW50LnZ1ZSdcbjwvc2Ny
The order matters, see https://github.com/vuejs/eslint-plugin-vue/issues/1781#issuecomment-1022735437.

In this suggestion, I adapted the explanation and example (also the link) and added a warning box:

````suggestion
:::warning Warning
The shorthand form is not always equivalent! If a prop accepts multiple types, but Boolean is not the first one, a shorthand prop won't pass `true`.
:::

```vue
<script>
export default {
  name: 'MyComponent',
  props: {
    bool: Boolean,
    boolOrString: [Boolean, String],
    stringOrBool: [String, Boolean],
  }
}
</script>
```

**Shorthand form:**

```vue
<MyComponent bool bool-or-string string-or-bool />
```

```
bool: true (boolean)
boolOrString: true (boolean)
stringOrBool: "" (string)
```

**Longhand form:**

```vue
<MyComponent :bool="true" :bool-or-string="true" :string-or-bool="true" />
```

```
bool: true (boolean)
boolOrString: true (boolean)
stringOrBool: true (boolean)
```

Those two calls will introduce different render result. See [this demo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBNeUNvbXBvbmVudCBmcm9tICcuL015Q29tcG9uZW50LnZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIFNob3J0aGFuZCBmb3JtOlxuICA8TXlDb21wb25lbnQgYm9vbCBib29sLW9yLXN0cmluZyBzdHJpbmctb3ItYm9vbCAvPlxuICBcbiAgTG9uZ2hhbmQgZm9ybTpcbiAgPE15Q29tcG9uZW50IDpib29sPVwidHJ1ZVwiIDpib29sLW9yLXN0cmluZz1cInRydWVcIiA6c3RyaW5nLW9yLWJvb2w9XCJ0cnVlXCIgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIk15Q29tcG9uZW50LnZ1ZSI6IjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIHByb3BzOiB7XG4gICAgYm9vbDogQm9vbGVhbixcbiAgICBib29sT3JTdHJpbmc6IFtCb29sZWFuLCBTdHJpbmddLFxuICAgIHN0cmluZ09yQm9vbDogW1N0cmluZywgQm9vbGVhbl0sXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwcmU+XG5ib29sOiB7e2Jvb2x9fSAoe3sgdHlwZW9mIGJvb2wgfX0pXG5ib29sT3JTdHJpbmc6IHt7Ym9vbE9yU3RyaW5nfX0gKHt7IHR5cGVvZiBib29sT3JTdHJpbmcgfX0pXG5zdHJpbmdPckJvb2w6IHt7c3RyaW5nT3JCb29sfX0gKHt7IHR5cGVvZiBzdHJpbmdPckJvb2wgfX0pXG4gIDwvcHJlPlxuPC90ZW1wbGF0ZT4ifQ==).
````

2022-02-10 11:12 UTC, FloEdelmann requested changes
Nice, this looks really good!

Only one problem I just noticed: The `never` option will also report native HTML shorthand attributes: `<input checked>` should become `<input checked="checked">`, not `<input :checked="true">`. Or is this actually allowed?

If it's allowed, please also add this test case to the "allowed" list to document this behavior.

If it isn't, we need a little more logic: Since one can use native HTML shorthand attributes like `hidden` also on components (e.g. `<MyComponent hidden>`), I think we also have to use suggestions instead of an autofix there: One for changing it into a longhand Vue prop, one for changing it into a longhand HTML attribute.

We might be a bit more clever about this and actually do autofix it in one case though: The shorthand attribute is on a known HTML element. Then we know that it should be autofixed to a longhand HTML attribute. But I think this is a nice-to-have improvement; only having suggestions in all cases would be fine for me.

2022-02-10 12:35 UTC, FloEdelmann commented
See also https://v3-migration.vuejs.org/breaking-changes/attribute-coercion.html

2022-02-11 02:14 UTC, g-plane commented
What about skipping native HTML elements, and just check components?

2022-02-11 06:57 UTC, FloEdelmann commented
That'd be fine for me, but still not catch the `<MyComponent hidden>` case. `hidden` might be a prop or an HTML attribute.

2022-02-11 11:06 UTC, FloEdelmann approved these changes
Nice, thanks for the improvements and the test cases! Please run `npm run update` one more time to update the docs (there is no autofix anymore). But this is not merge-blocking; we can do it afterwards.

2022-02-11 15:14 UTC, FloEdelmann approved these changes

2022-02-12 01:26 UTC, merged