Add `prefer-prop-type-boolean-first` rule
vuejs/eslint-plugin-vue pull request #1822
Opened 2022-03-21 10:17 UTC by g-plane

Close #1797 .

2022-03-21 11:00 UTC, FloEdelmann requested changes
Thanks, that looks really nice! I've commented a few small suggestions.

2022-03-22 01:27 UTC, g-plane commented on lib/rules/prefer-prop-type-boolean-first.js
> +    // eslint-disable-next-line eslint-plugin/require-meta-has-suggestions
I extracted the report logic into an outer `checkArrayExpression` function, and it can't be detected so I suppress this error.

2022-03-22 14:02 UTC, FloEdelmann commented on lib/rules/prefer-prop-type-boolean-first.js
> +    // eslint-disable-next-line eslint-plugin/require-meta-has-suggestions
I see. Then please add a comment to explain this:

```suggestion
    // eslint-disable-next-line eslint-plugin/require-meta-has-suggestions -- `context.report` with suggestion is not recognized in `checkArrayExpression`
```

2022-03-22 14:04 UTC, FloEdelmann approved these changes
Looks good from my side. Thanks!

2022-03-23 01:24 UTC, ota-meshi approved these changes
LGTM! Thank you!

2022-03-23 01:25 UTC, merged