docs: fix the warning note
vuejs/eslint-plugin-vue pull request #1858
Opened 2022-04-21 08:21 UTC by yammyxing

fix the warning note on rule conflicts between  vue/no-v-for-template-key and vue/no-v-for-template-key-on-child

2022-04-21 08:28 UTC, ota-meshi requested changes
I think the original note is correct.
However, I am not familiar with English, so I may have misunderstood.
Could you give me the details on this fix?

2022-04-21 10:03 UTC, FloEdelmann requested changes
I agree with @ota-meshi, the previous note was correct. But it was difficult to understand, so here is my approach to clear that up. See also the similar https://github.com/vuejs/eslint-plugin-vue/pull/1859#discussion_r855007958

2022-04-21 10:03 UTC, FloEdelmann commented on docs/rules/no-v-for-template-key.md
>  This rule conflicts with the [vue/no-v-for-template-key-on-child] rule.
```suggestion
This rule is targeted at Vue.js 2.x.
If you are using Vue.js 3.x, enable the [vue/no-v-for-template-key-on-child] rule instead. Don't enable both rules together; they are conflicting.
```

2022-04-22 14:00 UTC, yammyxing commented
ok, the approach is clear enough.

2022-04-22 14:03 UTC, yammyxing commented
> I think the original note is correct. However, I am not familiar with English, so I may have misunderstood. Could you give me the details on this fix?

seems like i get the meaning of 'use with' wrong, my bad [Lol]

2022-04-22 14:03 UTC, yammyxing commented on docs/rules/no-v-for-template-key.md
>  This rule conflicts with the [vue/no-v-for-template-key-on-child] rule.
ok, the approach is clear enough.

2022-04-22 14:41 UTC, FloEdelmann approved these changes

2022-04-22 14:46 UTC, merged