Add `vue/no-ref-object-destructure` rule
vuejs/eslint-plugin-vue pull request #1965
Opened 2022-09-10 02:43 UTC by ota-meshi

This PR adds `vue/no-ref-object-destructure` rule that reports the destructuring of ref objects causing the value to lose reactivity.

close #1949

2022-09-10 10:59 UTC, FloEdelmann requested changes
Just a quick look because I don't have time for a full review of this big PR.

2022-09-10 10:59 UTC, FloEdelmann commented on docs/rules/no-ref-object-destructure.md
> +This rule also supports Reactivity Transform, but Reactivity Transform is an experimental feature and may have false positives due to future Vue changes.
Please add a link to the RFC or other official docs here.

2022-09-10 10:59 UTC, FloEdelmann commented on tests/lib/rules/no-ref-object-destructure.js
> +    const value3 = computed(() => fn(count.value) /* ✓ GOOD */)
```suggestion
    const value1 = computed(() => count.value)
    const value2 = fn(count)
    const value3 = computed(() => fn(count.value))
```

2022-09-10 10:59 UTC, FloEdelmann commented on tests/lib/rules/no-ref-object-destructure.js
> +        const value1 = count.value /* ✗ BAD */
```suggestion
      const value1 = count.value
      const { value: value2 } = count
      const value3 = fn(count.value)
      const { value: value4 = 42 } = count
      if (foo) {
        const value1 = count.value
```

2022-09-10 11:46 UTC, ota-meshi commented
Thank you for the quick review! I have changed the part you commented on.

2022-09-10 12:37 UTC, FloEdelmann approved these changes
Thanks, that looks fine now. As noted earlier, I have not looked deeper into the other parts though.

2022-09-10 22:53 UTC, merged

2022-09-22 15:09 UTC, Tofandel commented
This seems to have caused a regression on the `vue/no-ref-as-operand` rule

```js
import {ref} from 'vue';

const someting = false;
let columns;

if (something) {
  const cols = ref([1]);
  columns = cols;
} else {
  columns = ref([2]);
}
```

This used to be fine, with the new version this causes 
```
 error  Must use `.value` to read or write the value wrapped by `ref()`  vue/no-ref-as-operand
 error  Must use `.value` to read or write the value wrapped by `ref()`  vue/no-ref-as-operand
```