feat: rule fixer for require-name-property
vuejs/eslint-plugin-vue pull request #2034
Opened 2022-11-10 09:42 UTC by 0xYootou

this is a pull request for issues: #2033

2022-11-10 13:46 UTC, FloEdelmann requested changes
Thanks for the suggestion and the implementation!

Can we always auto-fix this to the filename or should we rather only add a suggestion for that, which the user can manually apply?

Also, please see the issues below.

2022-11-10 13:46 UTC, FloEdelmann commented on lib/rules/require-name-property.js
> +    hasSuggestions: true,
You added a fixer, not suggestions.

2022-11-10 13:46 UTC, FloEdelmann commented on lib/rules/require-name-property.js
> +            return fixer.insertTextBefore(
Can you please add test cases for the fixer?

2022-11-10 13:49 UTC, 0xYootou commented
ok, i think add a suggestion for that is better too, i will rewrite the code and add test case.

2022-11-11 04:13 UTC, 0xYootou commented
i push new code for this feature, and add some new test case for this rule and suggestions.

2022-11-15 14:02 UTC, FloEdelmann requested changes
Thanks for the changes!

2022-11-16 23:37 UTC, ota-meshi approved these changes
LGTM! Thank you!

2022-11-16 23:37 UTC, merged