fix: [vue/component-name-in-template-casing] False positive for dynamic component in template
vuejs/eslint-plugin-vue pull request #2069
Opened 2023-01-01 05:19 UTC by horitaka

This pull request is a fix for issue #2048.

I have modified `vue/component-name-in-template-casing` to ignore the check of the vue built-in component as well as the html tag.

According to the [test code](https://github.com/vuejs/eslint-plugin-vue/blob/master/tests/lib/rules/component-name-in-template-casing.js#L815-L842), the error of the `<component>` seemed to be correct. However, I followed the expected behavior in the issue #2048 and fixed it so that the error does not occur.

2023-01-02 21:52 UTC, FloEdelmann requested changes
I don't think that built-in components should always be skipped. Rather, type-only imports should always be ignored in `<script setup>` for this rule.

2023-01-04 12:17 UTC, horitaka commented
@FloEdelmann Thank you for your review. I understood the expected behavior of this issue. I will fix it so that type-only imports are ignored.

2023-01-07 04:55 UTC, horitaka commented
@FloEdelmann I fixed to skip the check if components is type-only import. Could you review it again?

2023-01-07 12:41 UTC, FloEdelmann approved these changes
Looks good to me now. Thanks for fixing!

2023-01-07 12:49 UTC, ota-meshi approved these changes
LGTM! Thank you!

2023-01-07 12:49 UTC, merged