Add `vue/max-lines-per-block` rule
vuejs/eslint-plugin-vue pull request #2213
Opened 2023-06-14 07:28 UTC by lsdsjy

Closes #1443

2023-06-14 10:10 UTC, FloEdelmann requested changes
Looks good, thanks for contributing!

I have just two small suggestions.

2023-06-14 10:10 UTC, FloEdelmann commented on docs/rules/max-lines-per-block.md
> +- `style` ... Specify the maximum number of lines in &lt;style&gt; block. Won't enforce limitation if not specified.
```suggestion
- `script` ... Specify the maximum number of lines in `<script>` block. Won't enforce limitation if not specified.
- `template` ... Specify the maximum number of lines in `<template>` block. Won't enforce limitation if not specified.
- `style` ... Specify the maximum number of lines in `<style>` block. Won't enforce limitation if not specified.
```

2023-06-14 10:10 UTC, FloEdelmann commented on docs/rules/max-lines-per-block.md
> +```
We need to show which options are used in each example as headers:

````suggestion
### `{ template: 2 }`

<eslint-code-block :rules="{'vue/max-lines-per-block': ['error', { template: 2 }]}">

```vue
<!-- ✗ BAD -->
<template>
  <div>
    hi
  </div>
</template>
```

</eslint-code-block>

### `{ script: 1, skipBlankLines: true }`

<eslint-code-block :rules="{'vue/max-lines-per-block': ['error', { script: 1, skipBlankLines: true }]}">

```vue
<!-- ✓ GOOD -->
<script>

  console.log(1)
</script>
```
````

2023-06-14 11:34 UTC, FloEdelmann approved these changes
LGTM :slightly_smiling_face:

2023-06-18 11:19 UTC, ota-meshi approved these changes
Thank you!

2023-06-18 11:19 UTC, merged