Fix no-ref-as-operand and allow lint when ref as right operator
vuejs/eslint-plugin-vue pull request #2273
Opened 2023-08-11 07:36 UTC by lakb248

fix #2271

2023-08-14 00:42 UTC, ota-meshi commented
Thanks for this PR. 
However, I think that this PR change has caused false positives in the following usages.

```vue
<script setup lang="ts">
import { ref, Ref } from 'vue'
const refValue1: Ref<number>  = ref(0)
const maybeRefValue: Ref<number> | null = getMaybeRef()
const refValue2 = maybeRefValue || refValue1
console.log(refValue2.value)
</script>
```

I think we should keep track of how the result of the expression is used.
Also, I think the ternary operator could be improved if it would be possible to track the usage of the result of the expression.

2023-10-06 18:35 UTC, ota-meshi requested changes
https://github.com/vuejs/eslint-plugin-vue/pull/2273#issuecomment-1676517901

2024-09-24 09:01 UTC, grindpride commented
@ota-meshi @lakb248 
Maybe put the logic for this rule in a separate `no-ref-as-operand-strict` rule, or customize with a parameter (`strictCheck`) of the current one?
In my code there are no cases of the following type
```ts
const refValue1: Ref<number>  = ref(0)
const maybeRefValue: Ref<number> | null = getMaybeRef()
const refValue2 = maybeRefValue || refValue1
```
But errors with such case use are often encountered

```ts
const refValue1: Ref<number>  = ref(0)
if (refValue1) {
  //incorrect condition
}
```

2026-07-22 15:18 UTC, FloEdelmann commented
It's been nearly two years now without any activity, so I'm going to close this. Feel free to open a new PR!

2026-07-22 15:18 UTC, closed without merging