fix(no-useless-mustaches): escape < in fixes
vuejs/eslint-plugin-vue pull request #2389
Opened 2024-02-01 15:12 UTC by DMartens

Fixes #2384
I looked up the parser specification for the [inside tag case](https://html.spec.whatwg.org/multipage/parsing.html#data-state) for potential additional cases which would differ:
- `<`: already covered in the issue
- `EOF`: would already be an error
- `\0`: I guess/hope no one would do this but there is a [difference](https://play.vuejs.org/#eNp9kE1rAjEQhv9KmIsX2Ra8iRTa4qE9tKXtcS7LOq6r2UlIJrqw5L+bRPw4iLfJ+zwJ72SEV2urfSCYw0Kot7oWekFWahzVBPF5omLMxzQiL55uFJiC+MbwumurrTecXhiLCY3pbafJfVvpDHuEuSoks1prc/gsmbhA03PebKjZ3cm3fsgZwo8jT25PCBcmtWtJTnj590VDmi+wN6ugk/0A/pI3OuSOJ+0t8CrVvvFK24/eGicdt/9+OQixPy+Vi2YzFh8hfeP7g9WvdWfVrNxDjhCPljJ9KQ==)
- `&`: there are cases when combining the text with either before or [after the mustache](https://play.vuejs.org/#eNp9kLtuAjEQRX/FmiI0aFPQERQpiSiSIomSlG5Wy2RZ8HoszxhWWvnfsY14FIjOuude6YxHeHGu2gWEOSwEe2dqwWdtlRpHNXmoHfFExfik7eLxCsMUhBuy/11bbZhsWo95pKGh3nUG/ZeTjixrmKtCMquNof1HycQHnJ7yZo3N9ka+4SFnGr49MvodajgzqX2LcsTL308c0vsMe1oFk9p34A8ymZAdj7XXYFdJ+6pXbN97R1462/7xchC0fDoqi+ZmLH0N6Qvf7px+0Z1Vs7LTNkI8AFgmfGM=) but is also highly unlikely

So this PR only adds escaping `<` with `&lt;` in the fixer.

2024-02-02 05:37 UTC, ota-meshi requested changes
Thank you for working on the issue and thank you for looking into more details!
The code looks good to me.
Could you run `npm run lint:fix` to format the file?

2024-02-05 10:21 UTC, FloEdelmann commented
There is still a lint error, so please run `npm run lint:fix`.

2024-02-05 11:23 UTC, FloEdelmann approved these changes
Looks good to me, thanks for researching and fixing this bug!

2024-02-18 23:52 UTC, ota-meshi approved these changes
LGTM! Thank you!

2024-02-18 23:52 UTC, merged