implements proposed max-props rule
vuejs/eslint-plugin-vue pull request #2430
Opened 2024-03-15 16:13 UTC by kevsommer

This is a WIP PR that addresses issue #2429. 

It implements the rule for both, the Composition and Options API.

However, I haven't been able to get the case for `defineProps` with type-only declaration to work.

```vue
<script setup lang="ts">
defineProps<{ prop1: string, prop2: string, }>();
</script>
```

2024-06-25 08:27 UTC, kevsommer commented
Should work for `defineProps` with type-only declaration now.

2024-07-02 14:06 UTC, FloEdelmann requested changes
Thanks, this looks quite good! :slightly_smiling_face: 
I only have some minor nitpicks.

2024-07-02 14:06 UTC, FloEdelmann commented on docs/rules/max-props.md
> +## :mag: Implementation
"Nothing." is only the placeholder for when there are no rule options.

```suggestion
</eslint-code-block>

## :mag: Implementation
```

2024-07-02 14:06 UTC, FloEdelmann commented on lib/rules/max-props.js
> +        additionalProperties: false
```suggestion
        additionalProperties: false,
        minProperties: 1
```

2024-07-02 14:06 UTC, FloEdelmann commented on lib/rules/max-props.js
> +     */
```suggestion
    /** @type {Record<string, number>} */
```

2024-07-02 14:06 UTC, FloEdelmann commented on lib/rules/max-props.js
> +     */
```suggestion
    /**
     * @param {import('../utils').ComponentProp[]} props
     */
```

2024-07-02 14:06 UTC, FloEdelmann commented on tests/lib/rules/max-props.js
> +      </template>
Please remove the empty `<template>` blocks from the test cases, they don't add any value.

2024-07-03 10:01 UTC, kevsommer commented
Thank you for the review! I have implemented the requested changes :)

2024-07-03 10:17 UTC, FloEdelmann approved these changes
Looks good to me :slightly_smiling_face:

2024-07-13 01:06 UTC, ota-meshi approved these changes
LGTM! Thanks!

2024-07-13 01:07 UTC, merged