feat: add exclude tag names option
vuejs/eslint-plugin-vue pull request #2609
Opened 2024-11-16 05:57 UTC by waynzh

resolve #2605 

Add an `exclude` option to exclude specified tag names in the `vue/attribute-hyphenation` and `vue/v-on-event-hyphenation` rules.

2024-11-18 09:54 UTC, FloEdelmann requested changes

2024-11-18 09:54 UTC, FloEdelmann commented on docs/rules/attribute-hyphenation.md
> +    "exclude": []
Please rename the option (in both rules) to `ignoreTags`

2024-11-19 16:52 UTC, FloEdelmann requested changes

2024-11-19 16:52 UTC, FloEdelmann commented on docs/rules/attribute-hyphenation.md
>  - `"never"` ... Don't use hyphenated name except the ones that are ignored.
```suggestion
- `"always"` (default) ... Use hyphenated attribute name.
- `"never"` ... Don't use hyphenated attribute name.
```

2024-11-19 16:52 UTC, FloEdelmann commented on docs/rules/v-on-event-hyphenation.md
> +<eslint-code-block fix :rules="{'vue/v-on-event-hyphenation': ['error', 'never', { ignoreTags: ['/^custom-/'], autofix: true }]}">
```suggestion
### `"never", { "ignoreTags": ["/^custom-/"] }`

<eslint-code-block fix :rules="{'vue/v-on-event-hyphenation': ['error', 'never', { ignoreTags: ['/^custom-/'], autofix: true }]}">
```

2024-11-19 16:52 UTC, FloEdelmann commented on docs/rules/v-on-event-hyphenation.md
> +  <my-component v-on:custom-event="handleEvent" />
```suggestion
  <!-- ✓ GOOD -->
  <custom-component v-on:my-event="handleEvent" />

  <!-- ✗ BAD -->
  <my-component v-on:my-event="handleEvent" />
```

2024-11-19 16:52 UTC, FloEdelmann commented on lib/rules/attribute-hyphenation.js
> +    const ignoreTags = (
Please rename to `ignoredTagsRegexps` (also in the other rule).

2024-11-19 16:52 UTC, FloEdelmann commented on lib/rules/attribute-hyphenation.js
> +     */
```suggestion
    /** @param {string} name */
```

2024-11-19 16:52 UTC, FloEdelmann commented on lib/rules/attribute-hyphenation.js
> +    function isIgnoredTags(name) {
Please rename to `isIgnoredTagName` (also in the other rule).

2024-11-19 16:52 UTC, FloEdelmann commented on lib/rules/v-on-event-hyphenation.js
> +     */
```suggestion
    /** @param {string} name */
```

2024-11-19 16:52 UTC, FloEdelmann commented on tests/lib/rules/attribute-hyphenation.js
> +      options: ['never', { ignoreTags: ['VueComponent', '/^custom-/'] }]
Please also add a valid test case with `always` and `ignoreTags` (also for the other rule).

2024-11-19 16:52 UTC, FloEdelmann commented on tests/lib/rules/attribute-hyphenation.js
> +      options: ['never', { ignoreTags: ['CustomComponent'] }],
Please also add an invalid test case with `always` and `ignoreTags` (also for the other rule).

2024-11-20 02:40 UTC, waynzh commented
I've addressed the suggestions. Thanks for the review!

2024-11-20 08:16 UTC, FloEdelmann approved these changes
Looks good to me :slightly_smiling_face: 
Thanks for your contribution and for implementing the feedback!

2024-11-27 06:06 UTC, ota-meshi approved these changes
Looks good to me! Thank you!

2024-11-27 06:06 UTC, merged