feat(no-v-text-v-html-on-component): add ignore namespace option
vuejs/eslint-plugin-vue pull request #2610
Opened 2024-11-16 06:00 UTC by waynzh

resolve #2458

2024-11-18 09:46 UTC, FloEdelmann requested changes

2024-11-18 09:46 UTC, FloEdelmann commented on docs/rules/no-v-text-v-html-on-component.md
> +- `ignoreElementNamespaces` (`boolean`) ... Specify whether to ignore the namespace restrictions for SVG and MathML elements, so that the rule should not apply. Default is `false`.
```suggestion
- `ignoreElementNamespaces` (`boolean`) ... If `true`, always treat SVG and MathML tag names as HTML elements, even if they are not used inside a SVG/MathML root element. Default is `false`.
```

2024-11-18 09:46 UTC, FloEdelmann commented on docs/rules/no-v-text-v-html-on-component.md
> +  <mi v-text="content" /> <!-- <math> -->
```suggestion
  <g v-text="content" /> <!-- SVG element not inside of <svg> -->
  <mi v-text="content" /> <!-- MathML element not inside of <math> -->
```

2024-11-18 09:46 UTC, FloEdelmann commented on lib/rules/no-v-text-v-html-on-component.js
> +    function isCustomComponent(element) {
Maybe better add the new logic to the `isCustomComponent` util function with an optional second parameter `ignoreElementNamespaces`? E.g. something like this:

```js
  /**
   * Check whether the given node is a custom component or not.
   * @param {VElement} node The start tag node to check.
   * @param {boolean} [ignoreElementNamespaces=false] If `true`, ignore element namespaces.
   * @returns {boolean} `true` if the node is a custom component.
   */
  isCustomComponent(node, ignoreElementNamespaces = false) {
    if (
      hasAttribute(node, 'is') ||
      hasDirective(node, 'bind', 'is') ||
      hasDirective(node, 'is')
    ) {
      return true
    }

    const isHtmlName = this.isHtmlWellKnownElementName(node.rawName)
    const isSvgName = this.isSvgWellKnownElementName(node.rawName)
    const isMathName = this.isMathWellKnownElementName(node.rawName)

    if (ignoreElementNamespaces) {
      return !isHtmlName && !isSvgName && !isMathName
    }

    return (
      (this.isHtmlElementNode(node) && !isHtmlName) ||
      (this.isSvgElementNode(node) && !isSvgName) ||
      (this.isMathElementNode(node) && !isMathName)
    )
  }
```

2024-11-18 09:46 UTC, FloEdelmann commented on tests/lib/rules/no-v-text-v-html-on-component.js
Good test cases!

2024-11-19 08:27 UTC, FloEdelmann approved these changes
Looks good to me, thanks :slightly_smiling_face:

2024-11-19 08:28 UTC, FloEdelmann commented
The test failure is probably caused by an ESLint update, so no need to worry about this.

2024-11-27 06:02 UTC, ota-meshi approved these changes
LGTM! Thank you!

2024-11-27 06:03 UTC, merged