Add `vue/no-implicit-coercion` rule
vuejs/eslint-plugin-vue pull request #2639
Opened 2024-12-05 14:29 UTC by lozinsky

Closes #2638

2024-12-05 14:31 UTC, FloEdelmann approved these changes
Nice, looks good to me :slightly_smiling_face:

2024-12-05 14:37 UTC, FloEdelmann requested changes

2024-12-05 14:37 UTC, FloEdelmann commented on tests/lib/rules/no-implicit-coercion.js
However, I see that some tests are failing. Could you please have a look at them? Possibly you have to skip specific test cases using a `semver` check, see e.g. https://github.com/vuejs/eslint-plugin-vue/blob/master/tests/lib/rules/multiline-ternary.js.

2024-12-05 15:34 UTC, lozinsky commented on tests/lib/rules/no-implicit-coercion.js
Yes, thanks for the reference. Done.

2024-12-05 16:07 UTC, FloEdelmann approved these changes
Perfect, thank you :slightly_smiling_face:

2025-01-08 09:36 UTC, ota-meshi approved these changes
LGTM! Thank you!

2025-01-08 09:36 UTC, merged